### ISSUE TITLE
Pull Request Review Rewards 

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/plugins-wishlist#22]
Let's make a plugin to incentivize pull request reviewers specifically. Events to monitor and provide rewards for:

- Review state
   - Approved
   - Left comment
   - Requested changes
- Resolved conversations

All config should be quantitative, and follow the `targets` syntax as defined in `@ubiquibot/conversation-rewards`

```yml
resolved-conversation: 
   targets: [ ISSUER, ASSIGNEE, COLLABORATOR, CONTRIBUTOR ]
   reward: 5
review-state-approved: 
   targets: [ ISSUER, ASSIGNEE, COLLABORATOR ]
   reward: 50
review-state-commented: 
   targets: [ ISSUER, ASSIGNEE, COLLABORATOR ]
   reward: 50
review-state-rejected: 
   targets: [ ISSUER, ASSIGNEE, COLLABORATOR ]
   reward: 50
```
